sudo: false
cache:
  directories:
    - $HOME/.m2
language: java
jdk:
  - oraclejdk8
services:
  - redis
before_install:
  - git config user.name "$GIT_NAME"
  - git config user.email "$GIT_EMAIL"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials
  - gem install asciidoctor
  - ./spring-cloud-cluster-consul/src/main/bash/travis_install_consul.sh
install:
- ./mvnw install -P docs -q -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true
- ./docs/src/main/asciidoc/ghpages.sh
script:
- ./consul agent -server -bootstrap-expect 1 -data-dir /tmp/consul &
- '[ "${TRAVIS_PULL_REQUEST}" != "false" ] || ./mvnw -s .settings.xml deploy -P release -nsu -Dmaven.test.redirectTestOutputToFile=false'
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] || ./mvnw install -nsu -Dmaven.test.redirectTestOutputToFile=true'
env:
  global:
  - GIT_NAME="Dave Syer"
  - GIT_EMAIL=dsyer@pivotal.io
  - CI_DEPLOY_USERNAME=buildmaster
  - secure: "pMlvX73tFb+cUYIlinof7HkNH6iYsCRv3xsT/GrVoMY8gFhYy6x1Ki/prCHr+ssSDjTlLi/HlecJz5kH4HHYZyoxDoO52cE5tHDyvjRrkLZiGq7p0T5m2FLLiVk62KunGQP+KjCUQfLnMPKz1FxDRO2lDHRZw4VhLxLmj1awKFU="
